
name: Test single2
run-name: "Test single2 ( ${{github.event.inputs.pkg-name}} ${{github.event.inputs.pkg-version}})"
on:
  workflow_dispatch:
    inputs:
      x-cmd-pkg-version:
        description: 'x-cmd pkg version'
        required: true
        default: 'v0.0.2'
      x-cmd-pkg-branch:
        description: 'x-cmd pkg branch'
        required: true
        default: 'main'
      x-bash-pkg-branch:
        description: 'x-bash pkg branch'
        required: true
        default: 'main'
      x-bash-env-branch:
        description: 'x-bash env branch'
        required: true
        default: 'main'
      pkg-name:
        description: 'test candidate'
        required: true
      pkg-version:
        description: 'test candidate version'
        required: false

jobs:
  test-xbin:
    name: Build
    strategy:
      matrix:
        os: [ [self-hosted, macOS, ARM64] ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      ___X_CMD_GHACTION_X: x1
      ___X_CMD_PKG_VERSION: ${{ github.event.inputs.x-cmd-pkg-version }}
      ___X_CMD_PKG_BRANCH: ${{ github.event.inputs.x-cmd-pkg-branch }}
      ___X_BASH_PKG_BRANCH: ${{ github.event.inputs.x-bash-pkg-branch }}
      ___X_BASH_ENV_BRANCH: ${{ github.event.inputs.x-bash-env-branch }}
      ___X_CMD_PKG_CANDADITE: ${{github.event.inputs.pkg-name}}
      ___X_CMD_PKG_CANDADITE_VERSION: ${{github.event.inputs.pkg-version}}
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xws test-single
